#!/bin/bash

# Requires we be www-data user
sudo su www-data

# Install MMDC application
mkdir -p /var/www/node_modules/.bin
cd /tmp
echo '{ \"args\": [\"--no-sandbox\"] }' > ~/puppeteer-config.json
touch ~/.profile
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
source ~/.profile
nvm install 12.6.0
npm install mermaid.cli
rm ~/.profile

# EXIT the www-data user!
exit

# Add mmdc to standard path
sudo ln -s /var/www/node_modules/.bin/mmdc /usr/local/bin/mmdc